#!/usr/bin/env node

import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '../../..');

// Configuration
const REFERENCE_LOCALE = 'en';
const OUTPUT_FILE = 'src/i18n/types.generated.ts';

// Read reference translation file
async function readReferenceTranslations() {
  const filePath = path.join(ROOT_DIR, `src/i18n/locales/${REFERENCE_LOCALE}.ts`);
  try {
    const content = await fs.readFile(filePath, 'utf8');
    const exportMatch = content.match(/export\s+default\s+({[\s\S]*})\s*$/);
    if (exportMatch) {
      return new Function('return ' + exportMatch[1])();
    }
  } catch (error) {
    console.error(`Error reading ${REFERENCE_LOCALE}.ts:`, error.message);
    return {};
  }
}

// Generate TypeScript interface from object structure
function generateInterface(obj, interfaceName, indent = '') {
  let output = `${indent}export interface ${interfaceName} {\n`;
  
  const entries = Object.entries(obj);
  entries.forEach(([key, value], index) => {
    const isLast = index === entries.length - 1;
    
    // Escape key if needed
    const safeKey = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key) ? key : `'${key}'`;
    
    if (typeof value === 'string') {
      output += `${indent}  ${safeKey}: string;${isLast ? '' : ''}\n`;
    } else if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      // Generate nested interface
      const nestedInterfaceName = `${interfaceName}${key.charAt(0).toUpperCase() + key.slice(1)}`;
      output += `${indent}  ${safeKey}: ${nestedInterfaceName};${isLast ? '' : ''}\n`;
    } else {
      // Default to any for other types
      output += `${indent}  ${safeKey}: any;${isLast ? '' : ''}\n`;
    }
  });
  
  output += `${indent}}`;
  return output;
}

// Generate nested interfaces
function generateNestedInterfaces(obj, parentName, allInterfaces = []) {
  const mainInterface = generateInterface(obj, parentName);
  allInterfaces.push(mainInterface);
  
  // Generate interfaces for nested objects
  Object.entries(obj).forEach(([key, value]) => {
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      const nestedInterfaceName = `${parentName}${key.charAt(0).toUpperCase() + key.slice(1)}`;
      generateNestedInterfaces(value, nestedInterfaceName, allInterfaces);
    }
  });
  
  return allInterfaces;
}

// Generate translation key paths type
function generateKeyPaths(obj, prefix = '') {
  const paths = [];
  
  Object.entries(obj).forEach(([key, value]) => {
    const fullPath = prefix ? `${prefix}.${key}` : key;
    
    if (typeof value === 'string') {
      paths.push(`'${fullPath}'`);
    } else if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      // Skip plural and context variations in key paths
      if (!key.match(/_(one|other|zero|few|many|male|female|neutral|formal|informal)$/)) {
        paths.push(...generateKeyPaths(value, fullPath));
      }
    }
  });
  
  return paths;
}

// Generate namespace keys
function generateNamespaceKeys(obj) {
  return Object.keys(obj).map(key => `'${key}'`);
}

// Generate plural keys type
function generatePluralKeys(obj, prefix = '') {
  const pluralKeys = [];
  
  Object.entries(obj).forEach(([key, value]) => {
    const fullPath = prefix ? `${prefix}.${key}` : key;
    
    // Check if this is a plural base key
    const baseKey = key.replace(/_(one|other|zero|few|many)$/, '');
    if (baseKey !== key) {
      const basePath = prefix ? `${prefix}.${baseKey}` : baseKey;
      if (!pluralKeys.includes(`'${basePath}'`)) {
        pluralKeys.push(`'${basePath}'`);
      }
    } else if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      pluralKeys.push(...generatePluralKeys(value, fullPath));
    }
  });
  
  return pluralKeys;
}

// Generate the complete TypeScript file
function generateTypeScriptFile(translations) {
  const timestamp = new Date().toISOString();
  
  let output = `/**
 * Auto-generated translation types
 * Generated: ${timestamp}
 * DO NOT EDIT MANUALLY - This file is auto-generated by generate-types.js
 */

/* eslint-disable */

`;

  // Generate main translations interface
  const interfaces = generateNestedInterfaces(translations, 'Translations');
  output += interfaces.join('\n\n') + '\n\n';
  
  // Generate translation keys type
  const keyPaths = generateKeyPaths(translations);
  output += `export type TranslationKey = \n  ${keyPaths.join(' |\n  ')};\n\n`;
  
  // Generate namespace type
  const namespaceKeys = generateNamespaceKeys(translations);
  output += `export type Namespace = ${namespaceKeys.join(' | ')};\n\n`;
  
  // Generate plural keys type
  const pluralKeys = generatePluralKeys(translations);
  if (pluralKeys.length > 0) {
    output += `export type PluralKey = \n  ${pluralKeys.join(' |\n  ')};\n\n`;
  }
  
  // Generate helper types
  output += `// Helper types for translation functions\n`;
  output += `export type TFunction = (key: TranslationKey, options?: Record<string, any>) => string;\n\n`;
  
  output += `export type UseTranslationResult = {\n`;
  output += `  t: TFunction;\n`;
  output += `  i18n: {\n`;
  output += `    language: string;\n`;
  output += `    changeLanguage: (lng: string) => Promise<void>;\n`;
  output += `  };\n`;
  output += `  ready: boolean;\n`;
  output += `};\n\n`;
  
  // Generate interpolation types
  output += `// Interpolation parameter types\n`;
  output += `export interface InterpolationParams {\n`;
  output += `  [key: string]: string | number | boolean;\n`;
  output += `}\n\n`;
  
  // Generate plural options type
  output += `// Plural options\n`;
  output += `export interface PluralOptions extends InterpolationParams {\n`;
  output += `  count: number;\n`;
  output += `}\n\n`;
  
  // Generate context options type
  output += `// Context options\n`;
  output += `export interface ContextOptions extends InterpolationParams {\n`;
  output += `  context?: string;\n`;
  output += `}\n\n`;
  
  // Generate combined options type
  output += `// Combined translation options\n`;
  output += `export type TranslationOptions = InterpolationParams | PluralOptions | ContextOptions;\n\n`;
  
  // Export default translations type
  output += `// Default export type\n`;
  output += `declare const translations: Translations;\n`;
  output += `export default translations;\n`;
  
  return output;
}

// Main function
async function main() {
  try {
    console.log('🔧 Generating TypeScript types from translations...\n');
    
    // Read reference translations
    const translations = await readReferenceTranslations();
    
    if (!translations || Object.keys(translations).length === 0) {
      console.error(`❌ No translations found in ${REFERENCE_LOCALE}.ts`);
      process.exit(1);
    }
    
    // Generate TypeScript file
    const typeScriptContent = generateTypeScriptFile(translations);
    
    // Write output file
    const outputPath = path.join(ROOT_DIR, OUTPUT_FILE);
    await fs.writeFile(outputPath, typeScriptContent);
    
    // Count generated types
    const keyCount = generateKeyPaths(translations).length;
    const namespaceCount = Object.keys(translations).length;
    const pluralKeyCount = generatePluralKeys(translations).length;
    
    console.log('📊 Generation Summary:');
    console.log(`   Translation keys: ${keyCount}`);
    console.log(`   Namespaces: ${namespaceCount}`);
    console.log(`   Plural keys: ${pluralKeyCount}`);
    console.log(`\n✅ Types generated successfully!`);
    console.log(`   Output: ${OUTPUT_FILE}`);
    
  } catch (error) {
    console.error('❌ Type generation failed:', error);
    process.exit(1);
  }
}

// Run if called directly
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}