"""Admin dependencies."""

from .rbac import (
    RequirePermissions,
    RequireAnyPermission,
    check_resource_permission,
    get_user_permissions,
    RequireUserRead,
    RequireUserWrite,
    RequireUserDelete,
    RequireRoleRead,
    RequireRoleWrite,
    RequireRoleAssign,
    RequireContentRead,
    RequireContentWrite,
    RequireContentModerate,
    RequireAnalyticsRead,
    RequireAnalyticsAdmin,
    RequireSystemRead,
    RequireSystemWrite,
    RequireAuditRead,
    RequireAuditExport,
    RequireAdminAccess,
    RequireSuperAdmin,
)

__all__ = [
    "RequirePermissions",
    "RequireAnyPermission",
    "check_resource_permission",
    "get_user_permissions",
    "RequireUserRead",
    "RequireUserWrite",
    "RequireUserDelete",
    "RequireRoleRead",
    "RequireRoleWrite",
    "RequireRoleAssign",
    "RequireContentRead",
    "RequireContentWrite",
    "RequireContentModerate",
    "RequireAnalyticsRead",
    "RequireAnalyticsAdmin",
    "RequireSystemRead",
    "RequireSystemWrite",
    "RequireAuditRead",
    "RequireAuditExport",
    "RequireAdminAccess",
    "RequireSuperAdmin",
]