"""Refactor ingredient model to use JSON fields

Revision ID: d48a956a7a2e
Revises: c9a7b8e0f1d2
Create Date: 2025-07-09 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd48a956a7a2e'
down_revision = 'c9a7b8e0f1d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_ingredients', sa.Column('brand', sa.String(length=100), nullable=True, comment='Brand of the ingredient, if applicable'))
    op.add_column('common_ingredients', sa.Column('barcode', sa.String(length=50), nullable=True, comment='Barcode (EAN/UPC) of the ingredient'))
    op.add_column('common_ingredients', sa.Column('nutritional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Nutritional values per 100g (e.g., calories, proteins)'))
    op.add_column('common_ingredients', sa.Column('unit_conversions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Conversion factors to grams (e.g., {"cup": 120, "tbsp": 15})'))
    op.add_column('common_ingredients', sa.Column('allergens', postgresql.ARRAY(sa.String()), nullable=True, comment='List of allergens present in the ingredient'))
    op.add_column('common_ingredients', sa.Column('dietary_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Dietary flags (e.g., {"vegan": true, "gluten_free": false})'))
    
    op.create_index(op.f('ix_common_ingredients_barcode'), 'common_ingredients', ['barcode'], unique=True)

    # Drop the foreign key constraint first, assuming a default name if not specified in the original migration
    try:
        op.drop_constraint('common_ingredients_nutritional_value_id_fkey', 'common_ingredients', type_='foreignkey')
    except Exception:
        print("Constraint common_ingredients_nutritional_value_id_fkey not found, skipping drop.")

    op.drop_column('common_ingredients', 'nutritional_value_id')
    
    op.drop_table('common_nutritional_values')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_ingredients_barcode'), table_name='common_ingredients')
    op.drop_column('common_ingredients', 'dietary_flags')
    op.drop_column('common_ingredients', 'allergens')
    op.drop_column('common_ingredients', 'unit_conversions')
    op.drop_column('common_ingredients', 'nutritional_data')
    op.drop_column('common_ingredients', 'barcode')
    op.drop_column('common_ingredients', 'brand')

    # Re-create the common_nutritional_values table
    op.create_table('common_nutritional_values',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('calories', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('proteins_g', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('carbohydrates_g', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('fats_g', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('sugars_g', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('saturated_fats_g', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('trans_fats_g', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('monounsaturated_fats_g', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('polyunsaturated_fats_g', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('cholesterol_mg', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('fiber_g', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('salt_g', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('calcium_mg', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('sodium_mg', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('water_g', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('phe_mg', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_a_ug', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_b1_mg', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_b2_mg', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_b3_mg', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_b5_mg', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_b6_mg', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_b7_ug', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_b9_ug', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_b12_ug', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_c_mg', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_d_ug', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_e_mg', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('vitamin_k_ug', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Add back the nutritional_value_id column and foreign key
    op.add_column('common_ingredients', sa.Column('nutritional_value_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_common_ingredients_nutritional_value_id', 'common_ingredients', 'common_nutritional_values', ['nutritional_value_id'], ['id'])
    # ### end Alembic commands ###
